title: Präanalysetool Wiki
logo: ./images/icon.png
description: Benutzerhandbuch Präanalysetool (QGIS-Plug-in). <br/>Diese Anleitung wurde im Rahmen der Bachelorthesis BTh03 erstellt von <br/><br/>Fabian Rüfenacht<br/>Fachhochschule Nordwestschweiz<br/>Institut Geomatik<br/>Hofackerstrasse 30<br/>4132 Muttenz
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
favicon: ./images/icon.png
